name: brick_offline_first
description: A Brick domain that routes data fetching through local providers
  before remote providers.
homepage: https://github.com/greenbits/brick/packages/brick_offline_first
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'
  flutter: '>=1.8.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity: '>=0.4.3 <2.0.0'
  brick_core:
    path: ../brick_core
  brick_rest:
    path: ../brick_rest
  brick_sqlite:
    path: ../brick_sqlite
  brick_offline_first_abstract:
    path: ../brick_offline_first_abstract
  logging: any

dev_dependencies:
  test: ">=1.9.4 <2.0.0"
  mockito: ^4.0.0
  dart_style: ^1.2.4

  flutter_test:
    sdk: flutter
