version: 2
defaults: &defaults
  working_directory: ~/project
  docker:
    - image: cirrusci/flutter:latest

jobs:
  brick_build:
    <<: *defaults
    steps:
      - checkout
      - run:
          working_directory: ~/project/packages/brick_build
          command: flutter pub get
      - run:
          working_directory: ~/project/packages/brick_build
          command: pub run test

  brick_core:
    <<: *defaults
    steps:
      - checkout
      - run:
          working_directory: ~/project/packages/brick_core
          command: pub get
      - run:
          working_directory: ~/project/packages/brick_core
          command: pub run test

  brick_offline_first:
    <<: *defaults
    steps:
      - checkout
      - run:
          working_directory: ~/project/packages/brick_offline_first
          command: flutter pub get
      - run:
          working_directory: ~/project/packages/brick_offline_first
          command: flutter test

  brick_rest:
    <<: *defaults
    steps:
      - checkout
      - run:
          working_directory: ~/project/packages/brick_rest
          command: pub get
      - run:
          working_directory: ~/project/packages/brick_rest
          command: pub run test

  brick_sqlite:
    <<: *defaults
    steps:
      - checkout
      - run:
          working_directory: ~/project/packages/brick_sqlite
          command: flutter pub get
      - run:
          working_directory: ~/project/packages/brick_sqlite
          command: flutter test

  brick_sqlite_abstract:
    <<: *defaults
    steps:
      - checkout
      - run:
          working_directory: ~/project/packages/brick_sqlite_abstract
          command: pub get
      - run:
          working_directory: ~/project/packages/brick_sqlite_abstract
          command: pub run test

workflows:
  version: 2
  commit:
    jobs:
      - brick_build
      - brick_core
      - brick_offline_first
      - brick_rest
      - brick_sqlite
      - brick_sqlite_abstract
