name: brick_sqlite_abstract
description: Support for Brick SQLite that does not rely on dart:mirrors
homepage: https://github.com/greenbits/brick/packages/brick_sqlite_abstract
issue_tracker: https://github.com/greenbits/brick/issues
repository: https://github.com/greenbits/brick

version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: any
  brick_core:
    git:
      url: git@github.com:greenbits/brick.git
      path: packages/brick_core

dev_dependencies:
  test: ">=1.9.4 <2.0.0"
